apiVersion: v1
kind: Service
metadata:
  name: potion-shop-axum-k8s
spec:
  selector:
    app: potion-shop-axum-k8s
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30081
