apiVersion: v1
kind: Service
metadata:
  name: potion-shop-nextjs-k8s
  labels:
    app: potion-shop-nextjs-k8s
spec:
  type: NodePort
  selector:
    app: potion-shop-nextjs-k8s
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
