apiVersion: v1
kind: Service
metadata:
  name: potion-shop-k8s-dotnet
  labels:
    app: potion-shop-k8s-dotnet
spec:
  type: NodePort
  selector:
    app: potion-shop-k8s-dotnet
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30081
    protocol: TCP
    name: http
