apiVersion: v1
kind: Service
metadata:
  name: potion-shop-springboot-k8s
  labels:
    app: potion-shop-springboot-k8s
spec:
  type: NodePort
  selector:
    app: potion-shop-springboot-k8s
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
